services:
  nestjs:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"